S01_Activity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path('admin/', admin.site.urls),
]

django_practice/urls.py
from django.urls import path

from . import views

app_name = 'grocerylist'
urlpatterns = [
    path('', views.index, name='index'),
    path('groceryitem/<int:groceryitem_id>/', views.groceryitem, name='viewgroceryitem'),
    path('event/<int:event_id>/', views.event, name='viewevent'),
    path('register/', views.register, name='register'),
    path('change_password/', views.change_password, name='change_password'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('add_event/', views.add_event, name='add_event'),
    path('add_grocery/', views.add_grocery, name='add_grocery'),
]

django_practice/models.py
from django.db import models
from django.contrib.auth.models import User

class GroceryItem(models.Model):
    item_name = models.CharField(max_length=50)
    category = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="pending")
    date_created = models.DateTimeField('date created')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Event(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE)

django_practice/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError("This username is already taken.")
        return username

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddEventForm(forms.Form):
    event_name = forms.CharField(label='Event Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)
    status = forms.CharField(label='Status', max_length=50, required=False)

class AddGroceryForm(forms.Form):
	item_name = forms.CharField(label='Item Name', max_length=50)
	category = forms.CharField(label='Category', max_length=200)

django_practice/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

# local imports
from .models import GroceryItem, Event
from .forms import LoginForm, RegisterForm, AddEventForm, AddGroceryForm

# Create your views here.
def index(request):
    groceryitem_list = GroceryItem.objects.all()
    event_list = Event.objects.all()  # Fetch all events from the database
    context = {'groceryitem_list': groceryitem_list, 'event_list': event_list}
    return render(request, "groceryitem/index.html", context)


def groceryitem(request, groceryitem_id):

    # retrieves the item objects using 
    groceryitem = get_object_or_404(GroceryItem, pk=groceryitem_id)

    # response = "You are viewing the details of %s"
    return render(request, "groceryitem/groceryitem.html", model_to_dict(groceryitem))

def event(request, event_id):

    # retrieves the item objects using 
    event = get_object_or_404(Event, pk=event_id)

    # response = "You are viewing the details of %s"
    return render(request, "groceryitem/event.html", model_to_dict(event))


def register(request):
    context = {}

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            # Checks the database if a user with the same username already exists
            if User.objects.filter(username=username).exists():
                context['error'] = True
            else:
                user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email, password=password)
                user.is_staff = False
                user.is_active = True
                user.save()
                return redirect('grocerylist:login')
    else:
        form = RegisterForm()

    context['form'] = form  # Pass the form to the template for error display

    return render(request, "groceryitem/register.html", context)

def change_password(request):

    is_user_authenticated = False
    user = authenticate(username ="johndoe", password = "john1234")
    print(user)
    if user is not None:
        authenticated_user = User.objects.get(username='johndoe')
        authenticated_user.set_password("johndoe1")
        authenticated_user.save()
        is_user_authenticated = True

    context = {
        "is_user_authenticated" : is_user_authenticated
        }
    
    return render(request, "groceryitem/change_password.html", context)

def add_event(request):
    context = {}

    if request.method == 'POST':
        form = AddEventForm(request.POST)

        if form.is_valid():
            event_name = form.cleaned_data['event_name']
            description = form.cleaned_data['description']

            # Check the database if an event with the same name already exists
            duplicates = Event.objects.filter(event_name=event_name)

            # If no duplicates found, create a new Event
            if not duplicates:
                Event.objects.create(
                    event_name=event_name,
                    description=description,
                    date_created=timezone.now(),
                    user=request.user  # Set the user directly, no need for user_id=request.user.id
                )
                return redirect('grocerylist:index')  # Redirect to a success page or event list
            else:
                context['error'] = True  # Set the error flag in the context
        else:
            context['form'] = form  # Pass the form with errors back to the template

    return render(request, "groceryitem/add_event.html", context)

def add_grocery(request):
    context = {}

    if request.method == 'POST':
        form = AddGroceryForm(request.POST)

        if form.is_valid():
            item_name = form.cleaned_data['item_name']
            category = form.cleaned_data['category']

            # Check the database if a grocery item with the same name already exists
            duplicates = GroceryItem.objects.filter(item_name=item_name)

            # If no duplicates found, create a new GroceryItem
            if not duplicates:
                GroceryItem.objects.create(
                    item_name=item_name,
                    category=category,
                    date_created=timezone.now(),
                    user=request.user  # Set the user directly, no need for user_id=request.user.id
                )
            else:
                context = {
                    "error": True
                }
        else:
            # Handle the case when the form is not valid (e.g., display form errors)
            context['form'] = form

    return render(request, "groceryitem/add_grocery.html", context)


def login_view(request):
    # username = "johndoe"
    # password = "johndoe1"
    # user = authenticate(username=username, password=password)

    context = {}

    if request.method == 'POST':

        form = LoginForm(request.POST)
            # Returns a blank Login form
        if form.is_valid() == False:
            form = LoginForm()
        else:
            # Retrieves the information from the form
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            context = {
                "username": username,
                "password": password
            }
        if user is not None:
            # Saves the user's ID in the session using Django's session framework
            login(request,user)
            return redirect("grocerylist:index")
        else:
            # Provides context with error to conditionally render the error message
            context = {
                "error": True
            }


    return render(request, "groceryitem/login.html", context)

def logout_view(request):
    logout(request)
    return redirect("grocerylist:index")

django_practice/templates/groceryitem/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3">Add An Event</h1>
        {% if error == True %}
          <p class="text-danger">Duplicate event found</p>
        {% endif %}
        <form action="{% url 'grocerylist:add_event' %}" method="post">
          {% csrf_token %}

          <div class="mb-3">
              <label for="event_name">Event Name:</label>
              <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
          </div>

          <div class="mb-3">
              <label for="description">Description:</label>
              <textarea class="form-control" id="description" name="description" required>{{ description }}</textarea>
          </div>

          <div class="text-center">
              <input class="btn btn-success" type="submit" value="Add Event">
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}

django_practice/templates/groceryitem/add_grocery.html
{% extends 'base.html' %}

{% block title %}Add Grocery{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3">Add Grocery</h1>
        {% if error == True %}
          <p class="text-danger">Duplicate Grocery found</p>
        {% endif %}
        <form action="{% url 'grocerylist:add_grocery' %}" method="post">
          {% csrf_token %}

          <div class="mb-3">
              <label for="item_name">Item Name:</label>
              <input class="form-control" id="item_name" type="text" name="item_name" value="{{ item_name }}" maxlength="50" required>
          </div>

          <div class="mb-3">
              <label for="category">Category:</label>
              <textarea class="form-control" id="category" name="category" required>{{ category }}</textarea>
          </div>

          <div class="text-center">
              <input class="btn btn-success" type="submit" value="Add Grocery">
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}

django_practice/templates/groceryitem/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct</p>
{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated</p>
{% endif %}

django_practice/templates/groceryitem/event.html
{% extends 'base.html' %}

{% block title %}To Do Item{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ event_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>
	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'grocerylist:index' %}" class="text-light text-decoration-none">Back To Events</a>
	</button>
	
</div>

{% endblock %}

django_practice/templates/groceryitem/groceryitem.html
{% extends 'base.html' %}

{% block title %}To Do Item{% endblock %}
{% block content %}
<div class="text-center my-3">
	<h1>{{ item_name }}</h1>
	<h3>Category</h3>
	<p>{{ category }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>
	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'grocerylist:index' %}" class="text-light text-decoration-none">Back To Events</a>
	</button>

	
</div>

{% endblock %}

django_practice/templates/groceryitem/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1 class="text-center my-3">Welcome {{ user.first_name }} {{ user.last_name }}!</h1>
        
        {% if groceryitem_list %}
            <div class="container">
                <div class="row">
                    <h3 class="text-center mb-3">My Tasks</h3>
                    <ul class="list-group col-lg-2 offset-lg-5 text-center">
                        {% for groceryitem in groceryitem_list %}
                            <a href="{% url 'grocerylist:viewgroceryitem' groceryitem.id %}" class="text-decoration-none">
                                <li class="list-group-item">{{ groceryitem.item_name }}</li>
                            </a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% else %}
            <p class="text-center">No tasks have been created.</p>
        {% endif %}
        
        {% if event_list %}
            <div class="container">
                <div class="row">
                    <h3 class="text-center mb-3">My Events</h3>
                    <ul class="list-group col-lg-2 offset-lg-5 text-center">
                        {% for event in event_list %}
                            <a href="{% url 'grocerylist:viewevent' event.id %}" class="text-decoration-none">
                                <li class="list-group-item">{{ event.event_name }}</li>
                            </a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% else %}
            <p class="text-center">No events have been created.</p>
        {% endif %}
        
    {% else %}
        <h1 class="text-center my-3">You are not logged in.</h1>
        <p class="text-center">Kindly <a href="{% url 'grocerylist:login' %}">login</a>.</p>
    {% endif %}
{% endblock %}

django_practice/templates/groceryitem/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Login</h1>
				{% if error == True %}
					<p class="text-danger">Invalid user credentials, please check your username and password</p>
				{% endif %}
				<form action="{% url 'grocerylist:login' %}" method="post">
					<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
					<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
					{% csrf_token %}

					<div class="mb-3">
					    <label for="username">Username: </label>
					    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
					</div>

					<div class="mb-3">
					    <label for="password">Password: </label>
					    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Login">
					</div>

				</form>
			</div>
		</div>
	</div>
{% endblock %}

django_practice/templates/groceryitem/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <h1 class="text-center my-3">Register</h1>
        {% if error %}
          <p class="text-danger">Registration error: {{ error }}</p>
        {% endif %}
        <form action="{% url 'grocerylist:register' %}" method="post">
          {% csrf_token %}

          <div class="mb-3">
            <label for="username">Username:</label>
            <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="150" required>
          </div>

          <div class="mb-3">
            <label for="first_name">First Name:</label>
            <input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="30" required>
          </div>

          <div class="mb-3">
            <label for="last_name">Last Name:</label>
            <input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="30" required>
          </div>

          <div class="mb-3">
            <label for="email">Email:</label>
            <input class="form-control" id="email" type="email" name="email" value="{{ email }}" required>
          </div>

          <div class="mb-3">
            <label for="password">Password:</label>
            <input class="form-control" id="password" type="password" name="password" required>
          </div>

          <div class="mb-3">
            <label for="password2">Re-enter Password:</label>
            <input class="form-control" id="password2" type="password" name="password2" required>
          </div>

          <div class="text-center">
            <input class="btn btn-success" type="submit" value="Register">
          </div>

        </form>
      </div>
    </div>
  </div>
{% endblock %}